<?php

namespace TenebresBundle\Repository;

/**
 * PnjRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PnjRepository extends \Doctrine\ORM\EntityRepository
{
}
